driver:
  name: docker
  use_sudo: false
  provision_command:
    - sed -i -e 's/httpredir.debian.org/ftp.de.debian.org/g' /etc/apt/sources.list || true
    - apt-get update && apt-get install -y net-tools cron